### PR TITLE
WIP - Begin using Glide

### PR DESCRIPTION
**Pull request by VoR0220**
* needs more work to figure out how to properly declare and vendor in our dependencies, currently will not install dependencies
* solves one part of checklist in consolidated epm #900 and #929

### CODE REVIEW

**Comment by zramsay** [comment]
the dependencies need to remain checked-in but managed by the `glide.lock`

**Comment by VoR0220** [comment]
agree, but we need to define those dependencies first.

**Comment by zramsay** [comment]
did the circle.yml get updated?

**Comment by VoR0220** [comment]
no? Shouldn't have?

**Pull request closed without merging**
