### PR TITLE
agent: remove all code (currently unused)

### PR DESCRIPTION
**Pull request by zramsay**
- removes unused agent code (command has been commented out)
- if/when we want this feature back, it would benefit from a complete re-write anyway

### CODE REVIEW

**Comment by VoR0220** [comment]
No no no...I was going to use this.

**Comment by VoR0220** [comment]
Or atleast modify it.

**Comment by zramsay** [comment]
then document that somewhere.

**Comment by VoR0220** [comment]
My bad. Thought you knew bout the spec. I need a way to get IPFS hashes. And potentially deploy them...though that may come later, but if we have it right now it actually could be useful. I was actually wondering if you could help me understand IPFS better in terms of how we could structure it in terms of a repo since you seem to have actually worked deeper with it?

**Pull request closed without merging**
